### ISSUE TITLE
Paper or online quiz?

### ISSUE THREAD

**Issue by dfaulken** [umts/umasstransit.rodeo#1]
Paper quiz is simpler for us, harder for the graders. A single model needed to track quiz scores, and the graders would simply enter the score.

Online quiz is a little harder for us, but means that scoring is automatic. Harder still for us would be making the quiz configurable as part of the interface - but this isn't MVP so we could save that for next year.

Thoughts? (@sherson, @werebus)

**Comment by werebus** [comment]
I favor paper quiz for two reasons:

1.  It allows the quiz masters to be creative with the content of the quiz, making it kind of grade-school-worksheet-like,  which is a fun tone.

2.  It removes the requirement of an electronic device from participants and leaves it on judges.

**Comment by dfaulken** [comment]
Sounds good, I'll go with that. The quiz is worth 50 points also?

**Comment by werebus** [comment]
Yes, although in the past quiz designers weren't as good at keeping the points to 50. Some years we've had a factor in the spreadsheet that we multiplied by to get a score out of 50.

I think the quiz has actually been exactly 50 points the last 3 or 4 years, though.

**Comment by dfaulken** [comment]
https://github.com/umts/umasstransit.rodeo/commit/77376cb2698d9b04e29e315ddf97e7c633b617c4
