### ISSUE TITLE
Fix faye in production

### ISSUE THREAD

**Issue by dfaulken** [umts/umasstransit.rodeo#13]
Server is running on port 9292:

```
$ sudo netstat -plutn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:38570         0.0.0.0:*               LISTEN      14731/current
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      13910/mysqld
tcp        0      0 127.0.0.1:9292          0.0.0.0:*               LISTEN      15135/ruby
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1301/sshd
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      28813/passenger-sta
tcp6       0      0 :::80                   :::*                    LISTEN      29963/apache2
tcp6       0      0 :::22                   :::*                    LISTEN      1301/sshd
```

But Rails can't connect to it:

```
$ tail log/production.log
Errno::ECONNREFUSED (Failed to open TCP connection to 2016.umasstransit.rodeo:9292 (Connection refused - connect(2) for "2016.umasstransit.rodeo" port 9292)):
  app/controllers/participants_controller.rb:24:in `destroy'
```

And I don't have firewall issues either:

```
$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

Not sure what could be the issue here.

**Comment by werebus** [comment]
This is probably a hosts/routing problem. 

From your netstat, the service is bound on the loopback interface only. But, if Rails is configured to connect to umasstransit.rodeo, your server has to be configured to know that the route to that domain is through the loopback address. Check your hosts file?

**Comment by dfaulken** [comment]
Fixed by configuring rackup to serve at `0.0.0.0`. Though now that I've done #14 I'm struggling to get thin to use SSL.

**Comment by werebus** [comment]
It would be better not to have internal services listening on `0.0.0.0` if it can be avoided.  You should be able to do `127.0.0.1` as long as you have an entry in your hosts file that says that your server can find umasstransit.rodeo on that IP address.

**Comment by dfaulken** [comment]
Makes sense. I added to `/etc/hosts`:

```
127.0.0.1 umasstransit.rodeo
```

Is this correct? Still no change.

**Comment by dfaulken** [comment]
Also, is that correct for Faye? My understanding was that it isn't an internal service.

**Comment by werebus** [comment]
Hmmm. Looking back over what you posted, the host you're trying to connect to is `2016.umasstransit.rodeo` which is a different host than `umasstransit.rodeo`

I also notice that the default Ubuntu configuration may actually be something like

```
127.0.0.1 localhost
127.0.1.1 hostname.domain hostname
```

So, perhaps something like:

```
127.0.0.1 localhost
127.0.1.1 2016.umasstransit.rodeo umasstransit.rodeo somehostname
```

**Comment by werebus** [comment]
Oh, nevermind.  You're right the browser clients need to connect to is too.

**Comment by dfaulken** [comment]
Ok, so serving at `0.0.0.0` moves us from `ERR_CONNECTION_REFUSED` to `ERR_CONNECTION_CLOSED` with the Ruby error:

`OpenSSL::SSL::SSLError in FayeController#test SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A`

**Comment by dfaulken** [comment]
As far as I can tell, this has something to do with TLS version incompatibility.

**Comment by dfaulken** [comment]
Turns out thin wasn't using SSL at all.

I [posted to SO](http://stackoverflow.com/questions/36405627/thin-over-ssl-through-apache-doesnt-perform-handshake) but @werebus and I ended up figuring it out.

Thanks again @werebus!
