### ISSUE TITLE
SSL?

### ISSUE THREAD

**Issue by dfaulken** [umts/umasstransit.rodeo#14]
Since people will be logging in with passwords to a site which eventually results in handing out prize money, it might be nice to encrypt traffic.

**Comment by werebus** [comment]
Indeed. 

https://letsencrypt.org/

**Comment by dfaulken** [comment]
I ran into an issue using their CLI to set up a certificate - moved discussion to Slack

**Comment by dfaulken** [comment]
Fixed.
