### ISSUE TITLE
"You are not authorized" flash uses `:notice` instead of `:alert`

### ISSUE THREAD

**Issue by frothedoatmilk** [umts/umasstransit.rodeo#205]
Not a big thing, but here, in `application_controller.rb`:
https://github.com/umts/umasstransit.rodeo/blob/main/app/controllers/application_controller.rb#L21

It makes an access problem look chipper rather than something you should be paying attention to!

**Comment by dirschn** [comment]
I think you want `:alert`, not `:error` https://api.rubyonrails.org/classes/ActionDispatch/Flash.html

**Comment by benmelz** [comment]
I had that thought at first, but

https://github.com/umts/umasstransit.rodeo/blob/8ec4e6a3c79e6c8e227e0f0652094b09f16dd6ad/app/views/layouts/application.haml#L15

But although it's accepted (through direct flash hash setting - theres no custom flash type for redirects), it's largely unused it seems

**Comment by dirschn** [comment]
https://github.com/rails/rails/blob/9f1dec2ea5155205a880f6e6e232cf9ea6da2d8c/actionpack/lib/action_controller/metal/flash.rb#L16-L34

unless I'm missing something I don't think we've added any `:error` flashes? A quick test (in round-three) gives me an argument error when I used `:error`

**Comment by dirschn** [comment]
Nah forget me I still need to wake up. I just realized what I was looking at in your comment, and tried in rodeo and it works.
