### ISSUE TITLE
Travis / CodeClimate / Rubocop

### ISSUE THREAD

**Issue by dfaulken** [umts/umasstransit.rodeo#21]

**Comment by dfaulken** [comment]
Determined that @Anbranin would need to be a team owner to set up Travis and CC.

**Comment by dfaulken** [comment]
Looks like pushing to master didn't trigger a Travis build @Anbranin

**Comment by dfaulken** [comment]
Scratch that - you didn't actually push to master

**Comment by Anbranin** [comment]
wat

**Comment by dfaulken** [comment]
👍
