### ISSUE TITLE
Add bus number

### ISSUE THREAD

**Issue by dfaulken** [umts/umasstransit.rodeo#22]
I initially left out keeping track of bus numbers because we decided it wasn't an issue - @sherson suggested we add it back in for scenarios where judges don't know the participant and can't see the number, to doublecheck that they're entering scores for the right person.

+ [x] Bus model / participant belongs to bus
+ [x] Allow master of ceremonies to add buses
+ [x] Allow master of ceremonies to assign participants bus number along with participant number, and to change bus number after the fact
+ [x] Show bus number to judges along with participant name and number

Does this look like what's needed @sherson?

**Comment by sherson** [comment]
:+1: 

Allow master of ceremonies to change things (in case of a typo, or perhaps a bus breakdown at start line).

**Comment by dfaulken** [comment]
Added.

**Comment by sherson** [comment]
Thanks, looks great
