### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by dfaulken** [umts/umasstransit.rodeo#56]
In 2016 I just added people via the Rails console.

We could allow anyone to register and then admins to approve like I did on [secret-santa](https://github.com/dfaulken/secret-santa/tree/master/app/controllers/users_controller.rb), or @werebus suggested allowing the master of ceremonies to issue invitations.

**Comment by werebus** [comment]
Yes, I've used [devise-invitable](https://github.com/scambra/devise_invitable) in the past.  It's pretty nice.

If you want, you can override `invitation_limit` on your user model to use custom logic.  [Example](https://github.com/werebus/moretticamp/blob/master/app/models/user.rb#L30-L32).

**Comment by dfaulken** [comment]
In this case I might favor the approval method, just so that folks don't have to approach me or Pires at all in order to sign up.

**Comment by werebus** [comment]
Well, it changes the order of the interaction.  Approval first lets the user sign up, then requires the intervention of an admin. Invitation first requires the intervention of an admin, then lets the user get themselves registered.

Another possible advantage of the invitation method is that we *could* give *every* user some invitations.  That is, if you know someone who already has a login, that person can get you a login, allowing a friend-of-a-friend type verification.
