### ISSUE TITLE
Ability to "close" scoring?

### ISSUE THREAD

**Issue by werebus** [umts/umasstransit.rodeo#61]
We had a judge stop by to ask if he could amend an on-board score. It turns he could.

Should the master of ceremonies be able to declare scores "locked" or something?

**Comment by dfaulken** [comment]
Sure, no reason not to. I didn't implement it originally because the site was supposed to be pretty ephemeral.

**Comment by frothedoatmilk** [comment]
This would involve...a lot of work. The _correct_ way to do this would be to implement some high scope model `Competition` which would have a `locked` attribute, and would be the parent of `User`, `Maneuvers`, etc... Not really worth doing for a small feature which could be replaced by the honor code

**Comment by werebus** [comment]
FWIW, it doesn't have to be _quite_ as complicated as that. All `ManeuverParticipant`s, `CircleCheckScore`s, etc. belong to the "current" Roadeo by virtue of existing; we [wipe the database](https://github.com/umts/umasstransit.rodeo/blob/33ac805893e88781c3c6f0a00d83643e957eae89/lib/tasks/reset.rake#L3-L15) every year.

**Comment by dirschn** [comment]
I would think maybe a custom validation tied to some arbitrary thing that checks "if yes, update is valid, if no block it"

**Comment by werebus** [comment]
We actually have a place to tie into already:

https://github.com/umts/umasstransit.rodeo/blob/33ac805893e88781c3c6f0a00d83643e957eae89/app/models/user.rb#L21-L23

If this method returns false, then only Admins and the Master of Ceremonies can access any of the routes that allow entering or modifying scores.

**Comment by frothedoatmilk** [comment]
The problem was figuring out what the "arbitrary thing" was, I was in the mindset of "do it right the first time," but I could just tie in into some existing model, since this needs to persist. Sounds like a job for the user model!

**Comment by dirschn** [comment]
The "arbitrary thing" is what @werebus linked above, that method should be modified to accommodate your needs

**Comment by frothedoatmilk** [comment]
My problem is not the tie in, it's how do I properly persist the setting for locking the code? Another solution I had was to add an attribute to every user, something like `lock_scores`, and if any admin or MC has it set to true, you lock scores? It felt jank initially which is why I didn't implement that way

**Comment by werebus** [comment]
Yeah, I didn't have an objection to a `Competition` or `Event` object or whatever. It just doesn't need to be all that deeply connected to any other objects in the database. There also only ever needs to be one of them. Elsewhere, we've [rolled our own "singleton" object](https://github.com/umts/st-pax/blob/main/app/models/issue_token.rb) in the past.

Something like...

```ruby
class Competition < ApplicationRecord
  validates :singleton, inclusion: { in: [0] }, uniqueness: true

  class << self
    delegate :open?, to: :instance

    def instance
      create_with(singleton: 0).first_or_create
    end
  end
end
```

**Comment by frothedoatmilk** [comment]
I did not see this message, I ended up doing what I mentioned above because it would also let you see who is locking the scores, which seemed useful to me (someone locks scores, you don't know why, figure out problem?)

**Comment by dirschn** [comment]
> Something like...

just went on a whole rabbit hole at @frothedoatmilk's expense, I don't see why we should roll our own when we have a true [`Singleton`](https://ruby-doc.org/3.1.4/stdlibs/singleton/Singleton.html) module at our disposal. Was that written before it existed? or did they not know it was there?
