### ISSUE TITLE
Prevent access to "new" page for maneuver participant after one has been created

### ISSUE THREAD

**Issue by Anbranin** [umts/umasstransit.rodeo#63]
Since there are duplicate paper sheets and a lot of entering scores after-the-fact has to be done, it would be far better if the `ManeuverParticipants#new` page were simply inaccessible -- or redirected to the edit page -- after one had been saved.

**Comment by dfaulken** [comment]
Worth pointing out that the only way to get there is by URL manipulation, but yes, agreed.
