### ISSUE TITLE
'Next' button in addition to 'Save and next'

### ISSUE THREAD

**Issue by dfaulken** [umts/umasstransit.rodeo#65]

**Comment by werebus** [comment]
Interestingly, the following discussion happened in the office this year:

1.  Pires complained about judges skipping people.
2.  I expressed confusion about how they were even doing that.
3.  Further investigation revealed that all the "skips" were actually the judge just — I dunno — leaving. That is, all the missing maneuvers were missing all the way to the end.

Is it definitely a thing we want to do: make skipping easier?

**Comment by werebus** [comment]
Given that Pires complained when he thought people were doing what this feature would allow them to do, I'm going to say we shouldn't do this.
