### ISSUE TITLE
Make user-configurable maneuvers

### ISSUE THREAD

**Issue by Anbranin** [umts/umasstransit.rodeo#66]
Right now umasstransit.rodeo and umasstransit.st.rodeo are two separate apps whose "maneuvers" aren't configurable by the user.
I'd like it if we had one application that any transit agency could take and add maneuvers to. That way, ST and Transit could take it and just make whatever maneuvers they wanted.
This project is pretty non-essential as these things go, but could be a good learning experience and also fun.

**Comment by werebus** [comment]
Closes umts/umasstransit.st.rodeo#1
