### ISSUE TITLE
App configuration

### ISSUE THREAD

**Issue by werebus** [umts/umasstransit.rodeo#72]
Even if `st` gets merged some day (#66, #20), there will still be some customization between the two. Those things might be good to put in some sort of application config. Things that come to mind:

*  Organization / Event name
*  Year?
*  Background color

**Comment by dfaulken** [comment]
Background color?

**Comment by werebus** [comment]
Beats me, all I know is one of them is blue and the other is brown.

https://github.com/umts/umasstransit.rodeo/commit/fdbf2e4631fcf231110d9dccaaa4272610ece284
