### ISSUE TITLE
Deny users

### ISSUE THREAD

**Issue by werebus** [umts/umasstransit.rodeo#92]
For example, currently in production:

![2019-04-26_12-01](https://user-images.githubusercontent.com/240275/56820897-10657100-681b-11e9-8858-76fc0a3ef1df.png)

I think I _won't_ click that "approve" button.

**Comment by Anbranin** [comment]
That's discrimination

**Comment by werebus** [comment]
Of course there _is_ a delete button on the "Roles" page if you really want to obliterate an unapproved user.
